# Generated by Django 3.1.2 on 2020-11-19 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='test_master',
            fields=[
                ('test_pk', models.AutoField(primary_key=True, serialize=False, verbose_name='プライマリキー')),
                ('id', models.IntegerField(unique=True, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名')),
                ('number', models.IntegerField(verbose_name='値')),
            ],
        ),
    ]
