# Generated by Django 3.1.2 on 2020-11-19 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formman', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='test_master',
            new_name='TestMaster',
        ),
    ]
